server:
  port: 9201
spring:
  application:
    name: castle-service-invoker
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1500
      circuitBreaker:
        requestVolumeThreshold: 3
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/