server:
  port: 9201
spring:
  application:
    name: castle-service-invoker
management:
  security:
    enabled: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/