server:
  port: 8080
spring:
  jpa:
    database: mysql
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.2.151:3306/hdvon_itsm?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: qwe123
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 50
      pool-name: blah
  data:
    jpa:
      repositories:
        enabled: false
  thymeleaf:
    encoding: UTF-8
    content-type: text/html
    cache: false
  messages:
    basename: default
security:
  basic:
    enabled: false